
name: Create crate dist
on:
  push:
    tags:
      - '**'

jobs:
  crate-dist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create crate dist
        uses: projg2/crate-dist-action@v1
        with:
          directories: tui-module
          dist-filename: qobine-2026-08-06-pre-crates.tar.xz
          run-cargo-update: false

